server/telega-pngext.c
when flag is 0, pipe2 is same as pipe
macOS don't have pipe2, use pipe can make it compatiple with macOS.
=> change pipe2 to pipe

telega-server.el
If user change default coding system, telega may failed to send non-ASCII
message and core dumped. This PR can fix this.
How to reproduce:
-  `(set-default-coding-systems 'gbk)`, or any other except utf-8 series.
- Start telega and send any message contains non-ASCII character.
- telega-server core dumped.
----
#
=> [fix] Force utf-8 while starting telega server.

README.md
Emacs-mac has added a new compiling option to compile emacs to use rsvg
instead of webkit to render svg files, witch fixed the hangup issue.
But there's still one issue exist with emacs-mac: stickers cannot be
displayed correctly.
=> update current status on emacs-mac

README.md
This pull request adds information about how to retrieve telega and tdlib from GNU Guix. It also has information on contacting me on Github in your issue tracker for issues related to the Guix installation option. Thanks!
=> Modify the README.md to reflect option to install from GNU Guix

README.md
This change revises the README to reflect the new GUIX label for the issue tracker as well as how to properly use it.
=> Update section on GUIX to reflect issue tracker label.

etc/guix.scm, guix.scm
This file makes it easier to contribute to upstream development of telega for people using GNU Guix. It should not conflict with MELPA, and should merge easily. It is a standard practice to use this file to spin up development containers (similar to pyvenv, but far more flexible). Let me know what you think, thanks!
=> Add guix.scm file for development of telega on GNU Guix.

etc/guix.scm
This is a revision to the previous pull request. This is a more hygienic way to ensure that ffmpeg functionality is given to emacs-telega on build-time.
=> Patch `ffplay` and `ffmpeg` paths instead of propagating ffmpeg input.

etc/guix.scm
Fixes
```
brettg@oryx ~/Repos/telega.el [env]$ bear guix build -f ./etc/guix.scm 
/home/brettg/Repos/telega.el/etc/guix.scm:149:5: In procedure inputs:
error: ffmpeg: unbound variable
hint: Did you forget `(use-modules (gnu packages video))'?
```
=> Add video module to guix.scm

telega-chat.el
=> Revert change to error string for Emacs Lisp consistency

etc/guix.scm
This will provide company-based completion support OOTB for users of Telega on GNU Guix, without having to install company themselves.
=> Add emacs-company as an input to emacs-telega.

README.md, server/Makefile
Builds the rpath for the Telegram library into the `telega-server`
binary so that it will be found automatically when starting
`telega-server`, regardless of where `LIBS_PREFIX` is pointing.
=> server/Makefile: Build library rpath into server

telega-customize.el
`C-h v telega-use-message-database` -> try to customize -> `Symbol’s function definition is void: nil`. Fix it.
=> Fixup some defcustom variables :type

server/Makefile, telega-server.el
First of all, thanks for developing this. I cannot convey in words how happy I am to have a working telegram client on my OpenBSD desktop (telegram web does not count), and it's even within emacs!  You really made my day.
Talking about this proposal: from #199 I can see that some changes to the build system are planned after td 1.7 (I don't know when it's scheduled), so I tried to minimize the changes.  I'm making the path to make customizable, so one can (setq telega-make-command "gmake") before (telega-build-server).  The root Makefile already uses $(MAKE), so this setting is propagated when building the server.
Another possibility could be to change telega-build-server so it let the user change the command to execute when called with a prefix argument.  Now that I'm thinking of it, …
=> fix build on non-GNU systems

telega-customize.el, telega-tdlib-events.el
When adding a buffer for notifications with the tracking package, one can specify a list of faces to use for it in the modeline.  This is useful not only for appearance, but also because the face can be used to prioritize the notification, altering the order in which it is shown (via tracking-faces-priorities).  I think telega-username is a good candidate for this, at least as a default.
=> Use telega-username as the face of tracking mode-line notifications

telega-sort.el, telega-util.el
nativecomp produces the following error
`
error in process filter: telega-emoji-create-svg: Invalid function: telega-svg-create
error in process filter: Invalid function: telega-svg-create
Error running timer ‘telega-server--idle-timer-function’: (invalid-function telega-ins-fmt)
`
=> fix nativecomp emacs cannot be used normally

telega-notifications.el
Now can set `dbus-debug` to `t` if somebody want to debug with notification
related issues.
=> Use dbus-ignore-errors in telega-notifications--close.

telega-chat.el, telega-customize.el
While "attach-member" might be consistent with the other "attach-*" functions, given the nature of the command and the consequences of misuse as well as the lack of confirmation it is important to make it clear that this adds a NEW member rather than mentioning someone who is already a member.
=> Rename the function telega-chatbuf-attach-member to something more intuitive.

telega-chat.el
The canonical way to test wihin a minibuffer is via `minibufferp`. The
old way of `(eq major-mode 'minibuffer-inactive-mode)` will no longer
work after 55db25b257 in Emacs master branch (see Emacs bug 47150 for
details). This commit fixes an old bug related to the implementation of
when is the minibuffer in minibuffer-inactive-mode. After the commit, we
have minibuffer-mode and minibuffer-inactive-mode.
=> Use canonical test for within a minibuffer

telega-util.el, test.el
Basically a backport of [this](https://github.com/zevlg/telega.el/commit/5e20c82918219cfc8555d17ebc6818c1d79fa62c) commit into `releases` branch.
=> Remove `cl--plist-remove' usage in telega stable branch

telega-chat.el, telega-customize.el, telega-util.el
Optionally guess default directory from dired buffers when picking
attachments.  By default, inherit user's `dired-dwim-target`
setting (dynamically).
In `telega-describe-chat--inserter` you set dir to nil explicitly.  I did not change that.
=> [enh] Support dired-dwim-target

telega-customize.el
It's even highlighted in the docstring of `custom-declare-variable` but I missed it:
> DEFAULT should be an expression to evaluate to compute the default value,
> not the default value itself.
=> [fix] `custom-declare-variable' wants a form rather than a value

telega-ffplay.el, telega-msg.el, telega-vvnote.el
telega-vvnote-voice-record-args, telega-vvnote-video-record-args
telega-msg-open-video-note use introdused telega-vvnote--has-audio-inputs
to dynamicaly check the supported audio inputs.
=> [add] Dynamic check of supported audio inputs

telega-root.el
Original func fails to wrap backwards from the end of buffer 
while n is negative. 
Paving infrastructure for the implementation of following commands:
```
(defun telega-root-prev-unread ()
"Move point to the previous chat with unread message."
(interactive)
(telega-root-next-unread -1))
(defun telega-root-prev-important()
"Move point to the previous important chat."
(interactive)
(telega-root-next-important -1))
(defun telega-root-prev-mention()
"Move point to the previous chat with mention."
(interactive)
(telega-root-next-mention -1))
(defun telega-root-prev-reaction ()
"Move point to the previous chat with unread reaction."
(interactive)
(telega-root-next-reaction -1))
```
=> Support wrap backwards from end of buffer

telega-tdlib-events.el
I changed "discaded" to "discarded" in the telega--on-updateCall function (telega-tdlib-events.el)
=> Correct a trivial event message misspelling

contrib/telega-bridge-bot.el, telega-msg.el
This PR does:
1. Extract `telega-msg--replied-message-fetch-callback` function. 
This way `contrib/telega-bridge-bot` doesn't need to override the whole `telega-msg--replied-message-fetch` function.
2. No longer hardcode username into first name, this will allow it to support the new user title format.
=> [contrib/telega-bridge-bot] Compatible with the latest updates from the master branch

contrib/telega-bridge-bot.el
Handle when the message body contains split characters.
=> [contrib/telega-bridge-bot] fix: when message body contains splitter

server/Makefile, server/telega-appindicator.c, telega-modes.el
Ubuntu 22 drops support of the `libappindicator` library in prior to `libayatana-appindicator`. It still has `libappindicator` in it's repo, but `ubuntu-desktop` package depends on ayatana version, so user can't just install `libappindicator`. You can check some background here - https://github.com/AyatanaIndicators/libayatana-appindicator/issues/30#issuecomment-950224779. 
Luckily, `libayatana-appindicator` interface is identical to `libappindicator`, so I added some additional ifs to use any of those libraries with `telega-appindicator`.
=> Add support for libayatana-appindicator library to telega-server

contrib/telega-bridge-bot.el
Username may not be a plain string, for example
```emacs-lisp
#("     " 0 2 (telega-display "𝐿") 2 4 (telega-display "𝑢") 4 6 (telega-display "𝑐") 6 8 (telega-display "𝑖") 8 10 (telega-display "𝑢") 10 12 (telega-display "𝑠"))
```
This can cause problems since we use it as a hash table key.
So here we use `(telega-tl-str content-text :text 'no-props)` to get the string without props.
=> [telega-bridge-bot] fix: get text without format

contrib/telega-bridge-bot.el
The `telega-user-title` function has modified in recent updates, so we also need update here.
Here we display both full_name and bot username like "Forward: Hello alice@matrix_bot",
=> [telega-bridge-bot] fix: Update telega-user-title function usage.

telega-user.el
If the user only sets the first_name, there will be extra spaces displayed.
This PR intends to fix it.
=> Remove duplicate spaces when user has only first_name.

telega-ins.el
In English, the phrase "last seen *in* $time" is referring to a time in the future (буквально, "в последний раз видели *через* $время").
To refer to a time in the past, the construct "last seen $time *ago*" ("видели $время *назад*") must be used.
This fixes #428.
=> telega-ins: correctly display last-seen time in the past

telega-ins.el
Hello,
I faced an error when receiving a link as `story_id` and `story_sender_chat_id` are both nil. I don't know if it is due to the use of emacs 29[1], but by simply testing if the value is available in addition to different to 0, it seems to solve the problem
[1] GNU Emacs 29.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-09-01
=> telega-ins: be resilient to missing story/story sender not defined when inserting a webpage

contrib/telega-bridge-bot.el
`telega-msg--pp` has been renamed to  `telega-chatbuf-msg--pp` in recent updates.
=> [contrib/bridge-bot] Fix: telega-msg--pp is now telega-chatbuf-msg--pp

contrib/telega-adblock.el, contrib/telega-bridge-bot.el, contrib/telega-emacs-stories.el
Rename all `messageForward*` to `message*`.
=> [contrib] [tdlib 1.8.21] rename messageForward* -> message*

contrib/telega-bridge-bot.el
Changes
- Now the forward chat id should be get in `:forward_info` `:from_chat_id`
- Display `fullname @username` in the reply message when that user is a bridge bot. Because the username of bridge bot are the same, so fullname needs to be added in order to distinguish them.
=> [contrib/telega-bridge-bot] Support tdlib 1.8.21

telega-util.el
In Podman 5.2.0, adding non-existent devices will throw an error.
> The --device option to podman create and podman run is no longer ignored when --privileged is also specified (https://github.com/containers/podman/issues/23132).
This PR will check if the device exists when add host devices to container.
=> Compatible with podman 5.2.0, check device existence.

etc/Dockerfile
This will get us a stable version of tdlib when we rebuild.
=> [fix] Dockerfile: set tdlib version by ARG

docs/telega-ellit.org, telega-chat.el, telega-customize.el
specifies Chat Temex for chats which can be deleted without typing confirmation
=> add `telega-chat-skip-delete-confirmation-for` custom option
